# Generated by Django 5.1.3 on 2024-11-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='info',
            field=models.CharField(max_length=50),
        ),
    ]
