# Generated by Django 5.1.3 on 2024-11-19 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_text_alter_service_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='service',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'unique_together': {('client', 'service')},
            },
        ),
    ]
