# Generated by Django 5.1.3 on 2024-11-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_client_service_client_name_clientservice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientservice',
            unique_together=set(),
        ),
    ]
